modLoader="kotlinforforge"
loaderVersion="[4.11,)"
license="${modLicense}"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
authors="${modAuthors}"
description='''${modDescription}'''
displayTest="IGNORE_ALL_VERSION"
[[dependencies.${modId}]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modId}]]
    modId="ldlib"
    mandatory=true
    versionRange="[1.0,2.0)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${modId}]]
    modId="trueuuid"
    mandatory=false
    versionRange="[1.0,2.0)"
    ordering="AFTER"
    side="BOTH"
